name: dson
version: 0.13.3
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson
environment:
  sdk: '>=2.0.0-dev <2.0.0'
dependencies:
  source_gen: 
  build: 
  analyzer: ^0.32.3
  logging: 
  dson_core: 
    git: https://github.com/sannysanoff/dson_core.git
  built_mirrors_core: 
  serializable_core:
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
dev_dependencies:
  test: 
  build_runner: 
